#!/bin/bash

BASE=`dirname $0`
PROG=`basename $0`

OPFS_PYTHON="${BASE}/../python27/bin/python"

if [ -x ${OPFS_PYTHON} ];then
    #using opfs python
    ${OPFS_PYTHON} ${BASE}/${PROG}.py $*
else
    #using system python
    python ${BASE}/${PROG}.py $*
fi
