DEST=~/opfs/bin
install:
	mkdir -p ~/opfs/bin
	install -m755 executer $(DEST)/opfsd
	install -m755 executer $(DEST)/opfsmount
	install -m644 opfsmount.py $(DEST)
	install -m644 opfsd.py $(DEST)
	install -m644 opfsc.py $(DEST)
	install -m644 opfsutil.py $(DEST)

